FROM joyzoursky/python-chromedriver:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x run_tests.sh

ENV DISPLAY=:99
ENV PYTHONUNBUFFERED=1

CMD ["./run_tests.sh"]
